`timescale 1 ns / 10 ps
// Generated from Simulink block 
module analysis_stub (
  input [256-1:0] adc_imag,
  input [256-1:0] adc_real,
  input [1-1:0] reset,
  input [10-1:0] valid1_dealy,
  input clk,
  input analysis_aresetn,
  input [5-1:0] analysis_s_axi_awaddr,
  input analysis_s_axi_awvalid,
  input [32-1:0] analysis_s_axi_wdata,
  input [4-1:0] analysis_s_axi_wstrb,
  input analysis_s_axi_wvalid,
  input analysis_s_axi_bready,
  input [5-1:0] analysis_s_axi_araddr,
  input analysis_s_axi_arvalid,
  input analysis_s_axi_rready,
  output [1-1:0] receive_vo1,
  output [1-1:0] receive_vo2,
  output [256-1:0] evenimag,
  output [256-1:0] evenreal,
  output [256-1:0] oddimag,
  output [256-1:0] oddreal,
  output [1-1:0] ifft_opvalid,
  output [256-1:0] dacimag,
  output [256-1:0] dacreal,
  output analysis_s_axi_awready,
  output analysis_s_axi_wready,
  output [2-1:0] analysis_s_axi_bresp,
  output analysis_s_axi_bvalid,
  output analysis_s_axi_arready,
  output [32-1:0] analysis_s_axi_rdata,
  output [2-1:0] analysis_s_axi_rresp,
  output analysis_s_axi_rvalid
);
  analysis sysgen_dut (
    .adc_imag(adc_imag),
    .adc_real(adc_real),
    .reset(reset),
    .valid1_dealy(valid1_dealy),
    .clk(clk),
    .analysis_aresetn(analysis_aresetn),
    .analysis_s_axi_awaddr(analysis_s_axi_awaddr),
    .analysis_s_axi_awvalid(analysis_s_axi_awvalid),
    .analysis_s_axi_wdata(analysis_s_axi_wdata),
    .analysis_s_axi_wstrb(analysis_s_axi_wstrb),
    .analysis_s_axi_wvalid(analysis_s_axi_wvalid),
    .analysis_s_axi_bready(analysis_s_axi_bready),
    .analysis_s_axi_araddr(analysis_s_axi_araddr),
    .analysis_s_axi_arvalid(analysis_s_axi_arvalid),
    .analysis_s_axi_rready(analysis_s_axi_rready),
    .receive_vo1(receive_vo1),
    .receive_vo2(receive_vo2),
    .evenimag(evenimag),
    .evenreal(evenreal),
    .oddimag(oddimag),
    .oddreal(oddreal),
    .ifft_opvalid(ifft_opvalid),
    .dacimag(dacimag),
    .dacreal(dacreal),
    .analysis_s_axi_awready(analysis_s_axi_awready),
    .analysis_s_axi_wready(analysis_s_axi_wready),
    .analysis_s_axi_bresp(analysis_s_axi_bresp),
    .analysis_s_axi_bvalid(analysis_s_axi_bvalid),
    .analysis_s_axi_arready(analysis_s_axi_arready),
    .analysis_s_axi_rdata(analysis_s_axi_rdata),
    .analysis_s_axi_rresp(analysis_s_axi_rresp),
    .analysis_s_axi_rvalid(analysis_s_axi_rvalid)
  );
endmodule
