Root:
  XilinxZcu208:
    Application:
      AppRingBuffer:
        Adc:
          Ch[:]:
            ContinuousMode: 0x1
        Dac:
          Ch[:]:
            ContinuousMode: 0x1
      AdcSigGen:
        enable: True

        # Enabled: 0x0
        Enabled: 0x1

        Continuous: 0x1
      DacSigGen:
        enable: True

        Enabled: 0x0
        # Enabled: 0x1

        Continuous: 0x1
        ######################################################################
        # CsvFilePath: 'config/DacSigGen/1tone_19_531250MHz_all_channels.csv'
        # CsvFilePath: 'config/DacSigGen/1tone_21MHz.csv'
        # CsvFilePath: 'config/DacSigGen/1tone_1GHz.csv'
        # CsvFilePath: 'config/DacSigGen/2tone_1GHz_1MHzspacing.csv'
        # CsvFilePath: 'config/DacSigGen/Ntone_2GHz_blanksection.csv'
        # CsvFilePath: 'config/DacSigGen/zero_all_ch.csv'
        ######################################################################
      DspCoreWrapper:
        Analysis:
          enable: False
          Config[1]: 0
          Config[2]: 0x8
          Config[3]: 0x41
          Config[4]: 0
          Config[5]: 0
          Config[6]: 0xFFFFFFFF
          Config[7]: 0
          Config[8]: 10
        AppRingBuffer:
          Adc:
            Ch[:]:
              ContinuousMode: 0x1
          Dac:
            Ch[:]:
              ContinuousMode: 0x1